### ISSUE TITLE
UnboundLocalError: local variable 'train_results' referenced before assignment

### ISSUE THREAD

**Issue by ZixuanLiu4869** [cassidylaidlaw/orpo#1]
I am using the following command to train the policy for the tomato environment:
python -m occupancy_measures.experiments.orpo_experiments with env_to_run=$ENV reward_fun=proxy exp_algo=ORPO 'om_divergence_coeffs=['$COEFF']' 'checkpoint_to_load_policies=["'$BC_CHECKPOINT'"]' seed=$SEED experiment_tag=state-action 'om_divergence_type=["'$TYPE'"]'. 
I set the environment variable according to the readme.txt.
I encountered the following error:
Traceback (most recent calls WITHOUT Sacred internals):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/zixuan1/code/Users/Zixuan/orpo/occupancy_measures/experiments/orpo_experiments.py", line 774, in main
    result = algorithm.train()
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 400, in train
    raise skipped from exception_cause(skipped)
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 397, in train
    result = self.step()
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 853, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/anaconda/envs/azureml_py38/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 2838, in _run_one_training_iteration
    results = self.training_step()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/zixuan1/code/Users/Zixuan/orpo/occupancy_measures/agents/orpo.py", line 1193, in training_step
    train_results.update(train_results_safe_policy)
UnboundLocalError: local variable 'train_results' referenced before assignment

Additional information:
I changed the num_rollout_workers of the config using config = config.rollouts(num_rollout_workers=0) to get rid of the warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.

It seems that the problem happens at line 1177 of occupancy_measures/agents/orpo.py
The self.config.current_policy_id is "current", however, it is not in the train_batch.policy_batches.
I also print out my train_batch which looks like this:
MultiAgentBatch({'safe_policy0': SampleBatch(3000: ['obs', 'new_obs', 'actions', 'rewards', 'terminateds', 'truncateds', 'infos', 'eps_id', 'unroll_id', 'agent_index', 't', 'vf_preds', 'action_dist_inputs', 'action_logp', 'values_bootstrapped', 'advantages', 'value_targets'])}, env_steps=3000)
And it misses the "current" batch.

I am also wondering if the safe policy refers to the pi_base in Algorithm 1 in the paper. 

Thanks for your great work!

**Comment by cassidylaidlaw** [comment]
Thanks for the interest in our paper! If your machine has less than 10 CPUs, then as you noticed training will stall with the error message about a resource request. A way to fix this without receiving the error you saw is to instead set

    config.resources(num_cpus_per_worker=0.1)
   
This should allow all the workers to run without the error message and without needing to set `num_rollout_workers=0`, which will cause other problems. Let me know if this helps!

**Comment by ZixuanLiu4869** [comment]
Thanks for your great work. Everything works now!
